### ISSUE TITLE
Method return values are returning false on success, not true

### ISSUE THREAD

**Issue by gigapod** [felixgalindo/XBeeArduino#2]
The methods - like ```writeConfig()```, or ```setLoRaWANNwkKey()``` are returning false on success, not true as doc'd. 

The underlying implementation is returning the return code from the XBee C library, which defines success as 0 - which the returning method is casting to false. 

If I have time, I'll fix this and throw a PR to this repo.

-K

### Example:
Arduino lib implementation:
```c++
bool XBeeArduino::setLoRaWANNwkKey(const char* value) {
    if (moduleType_ == XBEE_LORA) {
        return XBeeLRSetNwkKey(xbee_, value);
    }
    return false;
}
```

The method XBeeLRSetNwkKey

```c++
bool XBeeLRSetNwkKey(XBee* self, const char* value) {
    uint8_t response[33];
    uint8_t responseLength;
    uint8_t paramLength = (value != NULL) ? strlen(value) : 0;
    int status = apiSendAtCommandAndGetResponse(self, AT_NK, value, paramLength, response, &responseLength, 5000);
    if(status != API_SEND_SUCCESS){
        XBEEDebugPrintEnabled("Failed to set Nwk Key\n");
    }
    return status;
}
```

And ```API_SEND_SUCCESS``` is:
```c++
#define API_SEND_SUCCESS 0
```

The updated return statement for XBeeLRSetNwkKey():
```c++
     return status == API_SEND_SUCCESS;
```

**Comment by felixgalindo** [comment]
This has been fixed and pushed to main.
