### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by gigapod** [felixgalindo/XBeeArduino#5]
Hi Felix!

I think this is a memory leak:
https://github.com/felixgalindo/XBeeArduino/blob/e84bb355c01ca61a855bbc20ff76b9632c21b532/src/xbee_lr.c#L772

At least I didn't see the call to free() at the end of the function.

Any reason why you couldn't just use a stack variable for packet?

**Comment by felixgalindo** [comment]
@gigapod , yes I will change to use a stack variable.
